Ui 구현
2giwon/UnsplashAndroid pull request #11
Opened 2021-09-23 15:19 UTC by 2giwon

- 뷰모델 생성
- UseCase 주입하여 랜덤 이미지 로드하도록 수정
- 버튼을 누르면 랜덤이미지를 다시 로드하도록 수정
- UI 구현
#9 Fix

2021-09-24 14:41 UTC, BeokBeok requested changes
작업하시느라 고생이 많으십니다.
약간의 코맨트를 작성하였습니다. :smile:

<details><summary>코드리뷰 우선순위 규칙 (P1~P3)</summary>
P1: 적극적으로 고민해주세요 (Request changes)
<br>
코드 수정이 반드시 필요하다고 판단되는 경우입니다.<br>
리뷰 요청자께서 만약 수용할 수 없는 상황이라면 적합한 의견을 들어 토론해주세요.
<br></br>
P2: 웬만하면 반영해 주세요 (Comment)
<br>
코드 수정을 권장하거나 리뷰 요청자께서 해당 코드를 작성하신 의도를 알고자 하는 경우입니다.<br>
리뷰 요청자께서는 가급적이면 이유를 들어 설명해주시거나 의견을 달아주세요.
<br></br>
P3: 반영해도 좋고 넘어가도 좋습니다 (Approve)
<br>
해당 의견을 반영하는 게 좋을지 고민해 보는 정도면 충분합니다.<br>
만약 리뷰 요청자께서 리뷰어의 의견을 반영하셨더라도 리뷰어에게 별도로 리뷰 요청을 드리지 않아도 됩니다.
</details>

2021-09-24 14:41 UTC, BeokBeok commented on app/src/main/java/com/egiwon/unsplashandroid/MainActivity.kt
> +    val viewModel: MainViewModel by viewModels()
P1. private 접근자를 붙여주세요.

2021-09-24 14:41 UTC, BeokBeok commented on app/src/main/java/com/egiwon/unsplashandroid/MainActivity.kt
> +        }
P2. 바인딩어뎁터를 활용하면 어떨까요?

2021-09-24 14:41 UTC, BeokBeok commented on app/src/main/java/com/egiwon/unsplashandroid/MainActivity.kt
> +        viewModel.getRandomImage()
P2. 하나의 함수에서 두 가지 이상의 일을 하고 있습니다.
하나의 함수가 하나의 일만 하도록 분리하면 어떨까요?

2021-09-24 14:41 UTC, BeokBeok commented on app/src/main/java/com/egiwon/unsplashandroid/MainViewModel.kt
> +    val image: LiveData<PhotoVO> get() = _image
P2. 타입은 Photo인데 변수명은 Image이네요
의미를 하나로 통일해서 변수명을 작성하면 어떨까요?

2021-09-24 14:41 UTC, BeokBeok commented on app/src/main/java/com/egiwon/unsplashandroid/MainViewModel.kt
> +    }
P2. 이미지를 불러오는 도중에 Exception이 발생하게 되면 어떻게 될까요?

2021-09-24 14:41 UTC, BeokBeok commented on app/src/main/java/com/egiwon/unsplashandroid/vo/PhotoVO.kt
> +    )
P3. companion object를 활용하는 것이 좋을 것 같아요
대체로 하나의 파일에는 하나의 역할만 하도록 하는 것이 좋은 것 같아요

2021-09-24 14:41 UTC, BeokBeok commented on app/src/main/res/layout/activity_main.xml
> +            android:layout_width="match_parent"
```suggestion
            android:layout_width="0dp"
```
P2. ConstraintLayout의 자식 뷰는 match_parent 대신 0dp를 권장합니다

2021-09-24 14:41 UTC, BeokBeok commented on app/src/main/res/layout/activity_main.xml
> +</layout>
```suggestion
    </androidx.constraintlayout.widget.ConstraintLayout>
    
</layout>
```
P3. close 태그 사이에는 한 줄 띄워주면 좋을 것 같아요

2021-09-24 14:41 UTC, BeokBeok commented on buildSrc/src/main/java/Dependencies.kt
> +    const val GLIDE_COMPILER = "com.github.bumptech.glide:compiler:$GLIDE_VER"
P3. Glide 관련 디펜던시끼리 묶을 수 있지 않을까요?

2021-09-27 13:58 UTC, 2giwon commented on app/src/main/res/layout/activity_main.xml
> +            android:layout_width="match_parent"
0dp 가 더 나은점이 뭔가요?

2021-09-27 14:24 UTC, 2giwon commented on app/src/main/java/com/egiwon/unsplashandroid/MainActivity.kt
> +    val viewModel: MainViewModel by viewModels()
수정했습니다. 91f51fb6d1ec40e12fabebb6edd2d17d91d6b85a

2021-09-27 14:24 UTC, 2giwon commented on app/src/main/java/com/egiwon/unsplashandroid/MainActivity.kt
> +        }
수정했습니다. d640999185c1e65084e3d9e63b24d327a281d36c

2021-09-27 14:25 UTC, 2giwon commented on app/src/main/java/com/egiwon/unsplashandroid/MainActivity.kt
> +        viewModel.getRandomImage()
중복코드를 제거하고 클릭 처리를 데이터바인딩으로 처리했습니다. 96a91042f8f668c2de7b2fbbfecce04d4bc3fbe0

2021-09-27 14:25 UTC, 2giwon commented on app/src/main/java/com/egiwon/unsplashandroid/MainViewModel.kt
> +    }
오류 발생시 토스트를 띄우도록 수정했습니다. 3ce40ece14810bd3c279602b37219005aa79c432

2021-09-27 14:25 UTC, 2giwon commented on app/src/main/java/com/egiwon/unsplashandroid/vo/PhotoVO.kt
> +    )
수정했습니다. 2523962fb63320cb44bdfa290fc9cac314c05808

2021-09-27 14:27 UTC, 2giwon commented on app/src/main/res/layout/activity_main.xml
> +</layout>
코드정리를 했습니다. d37cf95e3272d7503b8aa4184e2b948056ffc573

2021-09-27 14:30 UTC, 2giwon commented on buildSrc/src/main/java/Dependencies.kt
> +    const val GLIDE_COMPILER = "com.github.bumptech.glide:compiler:$GLIDE_VER"
수정했습니다. c955542e52cca2b64b6ac7ed6d4acb2f55189575

2021-09-27 14:31 UTC, 2giwon commented on app/src/main/java/com/egiwon/unsplashandroid/MainViewModel.kt
> +    val image: LiveData<PhotoVO> get() = _image
수정했습니다. a80d8ee75df6b93af0a38b1f38af1cafff41d2b4

2021-09-28 00:07 UTC, BeokBeok commented on app/src/main/res/layout/activity_main.xml
> +            android:layout_width="match_parent"
ConstraintLayout의 권장사항입니다.

ref. https://developer.android.com/training/constraint-layout#adjust-the-view-size

2021-09-28 00:07 UTC, BeokBeok commented on app/src/main/java/com/egiwon/unsplashandroid/MainViewModel.kt
> +        }
P3. UseCase에서 리턴타입을 코틀린에서 제공하는 Result로 Wrapping하면, 뷰모델에서 try-catch 문 대신 onSuccess, onFailure를 활용할 수 있습니다.

2021-09-28 00:07 UTC, BeokBeok commented on app/src/main/java/com/egiwon/unsplashandroid/MainViewModel.kt
> +    fun getRandomImage() = viewModelScope.launch {
P2. 라이프싸이클에 의해서 viewModelScope가 예기치못하게 종료되었을 때에는 어떻게 될까요?

2021-09-28 00:07 UTC, BeokBeok commented on app/src/main/java/com/egiwon/unsplashandroid/ext/ImageViewExt.kt
> +}
P2. 바인딩어뎁터를 extension으로 정의하게 되면 어떤 문제가 발생할까요?

2021-09-28 00:07 UTC, BeokBeok commented on app/src/main/java/com/egiwon/unsplashandroid/ext/ImageViewExt.kt
> +@BindingAdapter("urlToGlide")
P2. 다른 개발자가 봤을 때, 이 바인딩어뎁터를 활용하게 하려면 어떻게 하면 좋을까요?
prefix를 활용하면 어떨까요?

2021-09-28 00:07 UTC, BeokBeok commented on app/src/main/res/layout/activity_main.xml
> +                tools:src="@tools:sample/backgrounds/scenic" />
P3. 만약 액티비티에서 AppCompatActivity를 상속하고 있다면, AppCompatImageView와 ImageView는 동일하게 처리됩니다.

2021-10-01 14:52 UTC, 2giwon commented on app/src/main/res/layout/activity_main.xml
> +            android:layout_width="match_parent"
수정했습니다 e02487e6d2eb8f9a75a4b3e63c40c0af5e1d1d5f

2021-10-01 14:53 UTC, 2giwon commented on app/src/main/java/com/egiwon/unsplashandroid/MainViewModel.kt
> +        }
수정했습니다. e8bb303742be4990fda85ec795a67451440647ce

2021-10-01 14:54 UTC, 2giwon commented on app/src/main/java/com/egiwon/unsplashandroid/MainViewModel.kt
> +    fun getRandomImage() = viewModelScope.launch {
CoroutineExceptionHandler를 이렇게 처리한다는 걸 예전에 알았었는데 기억이 잘 안나서 좀 찾아봤습니다. 
이렇게 수정하는게 맞나요? 일단 Exception 처리를 해야 한다고 생각했습니다.
아니라면 알려주세요 🙏 
5e96ed62a5c6d6fea186e1d3e696a98e4fc5d960

2021-10-01 14:55 UTC, 2giwon commented on app/src/main/java/com/egiwon/unsplashandroid/ext/ImageViewExt.kt
> +}
다른 개발자들과 협업시 알려지지 않았을 경우 저 함수를 사용할 수 있겠군요 예전에 얘기한거 기억 납니다. 수정했습니다.
bc6eeae8639a5a3aaf0c8f23cfd627602ef9281e

2021-10-01 14:55 UTC, 2giwon commented on app/src/main/java/com/egiwon/unsplashandroid/ext/ImageViewExt.kt
> +@BindingAdapter("urlToGlide")
수정했습니다. bc6eeae8639a5a3aaf0c8f23cfd627602ef9281e

2021-10-01 14:56 UTC, 2giwon commented on app/src/main/res/layout/activity_main.xml
> +                tools:src="@tools:sample/backgrounds/scenic" />
수정했습니다. 166591132006c126fd4e3f4aaf4616c86d898395

2021-10-01 16:23 UTC, BeokBeok commented on app/src/main/java/com/egiwon/unsplashandroid/MainViewModel.kt
> +    fun getRandomImage() = viewModelScope.launch {
넵 맞습니다 👍

2021-10-01 16:27 UTC, BeokBeok approved these changes
클린 아키텍처를 학습하는 데 밑거름이 되었으면 좋겠습니다 😄 
수고하셨습니다 👍 
<img src="https://user-images.githubusercontent.com/48344355/108810482-8fca5400-75ee-11eb-9a24-9931a3877f9d.png" width="30%">

2021-10-01 16:27 UTC, BeokBeok commented on domain/src/main/java/com/egiwon/domain/usecase/GetRandomImageUseCase.kt
> +    suspend fun getRandomImage(): Result<PhotoData> = withContext(Dispatchers.IO) {
P3. 레트로핏은 기본적으로 suspend 함수인 경우에는, IO 디스패처에서 구동됩니다.
해서, withContext(Dispatchers.IO)는 생략이 가능합니다 😄

2021-10-04 10:44 UTC, BeokBeok commented
@2giwon 머지 가즈아

2021-10-05 13:16 UTC, merged