Data, Domain 모듈 생성
2giwon/UnsplashAndroid pull request #2
Opened 2021-09-02 14:56 UTC by 2giwon

- Data 모듈 생성
- Domain 모듈 생성
- Data 모듈이 Domain 모듈을 implementation
- APP 모듈이 Data, Domain 모듈을 implementation

2021-09-02 15:18 UTC, BeokBeok requested changes
작업하시느라 고생이 많으십니다.
약간의 코맨트를 작성하였습니다. :smile:

<details><summary>코드리뷰 우선순위 규칙 (P1~P3)</summary>
P1: 적극적으로 고민해주세요 (Request changes)
<br>
코드 수정이 반드시 필요하다고 판단되는 경우입니다.<br>
리뷰 요청자께서 만약 수용할 수 없는 상황이라면 적합한 의견을 들어 토론해주세요.
<br></br>
P2: 웬만하면 반영해 주세요 (Comment)
<br>
코드 수정을 권장하거나 리뷰 요청자께서 해당 코드를 작성하신 의도를 알고자 하는 경우입니다.<br>
리뷰 요청자께서는 가급적이면 이유를 들어 설명해주시거나 의견을 달아주세요.
<br></br>
P3: 반영해도 좋고 넘어가도 좋습니다 (Approve)
<br>
해당 의견을 반영하는 게 좋을지 고민해 보는 정도면 충분합니다.<br>
만약 리뷰 요청자께서 리뷰어의 의견을 반영하셨더라도 리뷰어에게 별도로 리뷰 요청을 드리지 않아도 됩니다.
</details>

2021-09-02 15:18 UTC, BeokBeok commented on build.gradle
> +        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
```suggestion
```
P2. 위에 중복되는 것 같은데 지워주시는 것이 좋아보입니다

2021-09-02 15:18 UTC, BeokBeok commented on data/build.gradle
> +    id 'kotlin-android'
P1. 데이터 모듈은 순수 kotlin 모듈이어야 합니다.
순수 kotlin 모듈로 변경해주세요.

2021-09-02 15:18 UTC, BeokBeok commented on domain/build.gradle
> +    id 'kotlin-android'
P2. 도메인 모듈은 순수 kotlin 모듈이어야 합니다.
순수 kotlin 모듈로 변경해주세요.

2021-09-02 15:44 UTC, 2giwon commented on build.gradle
> +        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
수정 했습니다. 6af763672722b9e83d36d0a50b7715774f3be9f9

2021-09-02 15:45 UTC, 2giwon commented on data/build.gradle
> +    id 'kotlin-android'
순수 kotlin 모듈 어떻게 바꾸나요?

2021-09-02 15:45 UTC, 2giwon commented on domain/build.gradle
> +    id 'kotlin-android'
순수 kotlin 모듈 어떻게 바꾸나요?

2021-09-02 15:49 UTC, 2giwon reviewed
finish review

2021-09-02 15:57 UTC, BeokBeok commented on data/build.gradle
> +    id 'kotlin-android'
New Module 에서 `Java or Kotlin Library` 로 만들어보시면, 순수 kotlin 모듈이 어떤 것인지 아실 수 있습니다 😄 

<img src="https://user-images.githubusercontent.com/48344355/131877011-57f1402c-7313-4256-9ebd-6f7da2d39778.png" width=30% />

2021-09-04 13:51 UTC, 2giwon commented on domain/build.gradle
> +    id 'kotlin-android'
수정했습니다. dfc47e9aec83941ecc17dadfaa2fff40500c5d9e

2021-09-04 13:51 UTC, 2giwon commented on data/build.gradle
> +    id 'kotlin-android'
수정했습니다. dfc47e9aec83941ecc17dadfaa2fff40500c5d9e

2021-09-04 13:53 UTC, BeokBeok approved these changes
<img src="https://user-images.githubusercontent.com/48344355/108810482-8fca5400-75ee-11eb-9a24-9931a3877f9d.png" width="30%">

2021-09-04 13:57 UTC, merged