Fix - Http 연동
2giwon/UnsplashAndroid pull request #5
Opened 2021-09-06 14:47 UTC by 2giwon

Fix #4 
- GET, https://api.unsplash.com/photos/random
- data 모듈에 랜덤 이미지 가져오는 api 구현

2021-09-06 14:55 UTC, BeokBeok requested changes
작업하시느라 고생이 많으십니다.
약간의 코맨트를 작성하였습니다. :smile:

<details><summary>코드리뷰 우선순위 규칙 (P1~P3)</summary>
P1: 적극적으로 고민해주세요 (Request changes)
<br>
코드 수정이 반드시 필요하다고 판단되는 경우입니다.<br>
리뷰 요청자께서 만약 수용할 수 없는 상황이라면 적합한 의견을 들어 토론해주세요.
<br></br>
P2: 웬만하면 반영해 주세요 (Comment)
<br>
코드 수정을 권장하거나 리뷰 요청자께서 해당 코드를 작성하신 의도를 알고자 하는 경우입니다.<br>
리뷰 요청자께서는 가급적이면 이유를 들어 설명해주시거나 의견을 달아주세요.
<br></br>
P3: 반영해도 좋고 넘어가도 좋습니다 (Approve)
<br>
해당 의견을 반영하는 게 좋을지 고민해 보는 정도면 충분합니다.<br>
만약 리뷰 요청자께서 리뷰어의 의견을 반영하셨더라도 리뷰어에게 별도로 리뷰 요청을 드리지 않아도 됩니다.
</details>

2021-09-06 14:55 UTC, BeokBeok commented on buildSrc/src/main/java/Dependencies.kt
> +
P2. Rx와 Coroutine은 따로 분리하시면 어떨까요?

2021-09-06 14:55 UTC, BeokBeok commented on buildSrc/src/main/java/Dependencies.kt
> +
P2. Rx와 Coroutine을 같이 쓰는 이유가 무엇인가요?

2021-09-06 14:55 UTC, BeokBeok commented on data/src/main/java/com/egiwon/data/datasource/ImageDataSourceImpl.kt
> +internal class ImageDataSourceImpl : ImageDataSource {
P1. RandomImageService를 생성자로 받아서 호출해주세요

2021-09-06 14:55 UTC, BeokBeok commented on data/src/main/java/com/egiwon/data/datasource/RandomImageService.kt
> +        @Query("client_id") clientId: String = "fwys9Zgd8cBBdZmwjdOQSKtfpotT3vVZJNnLxYMBhvk"
P1. 모든 API에 해당 쿼리가 적용되는 것으로 보이는데요
Interceptor를 구현해서 addQueryParameter 함수를 활용하면 어떨까요?

https://futurestud.io/tutorials/retrofit-2-how-to-add-query-parameters-to-every-request

2021-09-06 14:55 UTC, BeokBeok commented on data/src/main/java/com/egiwon/data/ImageRepositoryImpl.kt
> +internal class ImageRepositoryImpl {
P1. Repository 인터페이스를 만들어주시고, 해당 인터페이스를 implementation 해주세요

2021-09-07 14:37 UTC, 2giwon commented on buildSrc/src/main/java/Dependencies.kt
> +
c2104e0d8bdb3e05a7ac16bbb4e01136e8dbfad9 수정했습니다

2021-09-07 14:37 UTC, 2giwon commented on data/src/main/java/com/egiwon/data/datasource/ImageDataSourceImpl.kt
> +internal class ImageDataSourceImpl : ImageDataSource {
457d44afb9b76e087883b8c7a6b1e621a591816d 수정했습니다.

2021-09-07 14:37 UTC, 2giwon commented on data/src/main/java/com/egiwon/data/datasource/RandomImageService.kt
> +        @Query("client_id") clientId: String = "fwys9Zgd8cBBdZmwjdOQSKtfpotT3vVZJNnLxYMBhvk"
c8f4a470acd6ee8d3e3d0f3a957c776ea73afa02 수정했습니다.

2021-09-07 14:38 UTC, 2giwon commented on data/src/main/java/com/egiwon/data/ImageRepositoryImpl.kt
> +internal class ImageRepositoryImpl {
3238f25936c6752ed151f68d5cb9c14063183da0 수정했습니다.

2021-09-07 15:00 UTC, BeokBeok approved these changes
<img src="https://user-images.githubusercontent.com/48344355/108810482-8fca5400-75ee-11eb-9a24-9931a3877f9d.png" width="30%">

2021-09-07 15:00 UTC, BeokBeok commented on data/src/main/java/com/egiwon/data/api/RetrofitApi.kt
> +
P3. 라인 구분은 한 줄로 해주세요

2021-09-07 15:00 UTC, BeokBeok commented on data/src/main/java/com/egiwon/data/api/RetrofitApi.kt
> +            })
P3. 별도의 클래스에서 해당 Interceptor 만들어서 의존성 주입해도 좋을 것 같아요

2021-09-08 13:48 UTC, merged