UseCase 구현
2giwon/UnsplashAndroid pull request #8
Opened 2021-09-09 15:21 UTC by 2giwon

- usecase 구현 #7

2021-09-09 15:53 UTC, BeokBeok requested changes
<img src="https://user-images.githubusercontent.com/48344355/108810482-8fca5400-75ee-11eb-9a24-9931a3877f9d.png" width="30%">
작업하시느라 고생이 많으십니다.
약간의 코맨트를 작성하였습니다. :smile:

<details><summary>코드리뷰 우선순위 규칙 (P1~P3)</summary>
P1: 적극적으로 고민해주세요 (Request changes)
<br>
코드 수정이 반드시 필요하다고 판단되는 경우입니다.<br>
리뷰 요청자께서 만약 수용할 수 없는 상황이라면 적합한 의견을 들어 토론해주세요.
<br></br>
P2: 웬만하면 반영해 주세요 (Comment)
<br>
코드 수정을 권장하거나 리뷰 요청자께서 해당 코드를 작성하신 의도를 알고자 하는 경우입니다.<br>
리뷰 요청자께서는 가급적이면 이유를 들어 설명해주시거나 의견을 달아주세요.
<br></br>
P3: 반영해도 좋고 넘어가도 좋습니다 (Approve)
<br>
해당 의견을 반영하는 게 좋을지 고민해 보는 정도면 충분합니다.<br>
만약 리뷰 요청자께서 리뷰어의 의견을 반영하셨더라도 리뷰어에게 별도로 리뷰 요청을 드리지 않아도 됩니다.
</details>

2021-09-09 15:53 UTC, BeokBeok commented on data/src/main/java/com/egiwon/data/di/DataSourceModule.kt
> +        ImageDataSourceImpl(randomImageService)
P1. Binds 어노테이션이 적합해보입니다.
Provides와 Binds의 차이점은 무엇일까요?

2021-09-09 15:53 UTC, BeokBeok commented on data/src/main/java/com/egiwon/data/di/NetworkModule.kt
> +        retrofit.create(RandomImageService::class.java)
P2. 서비스 관련 부분은 따로 분리하면 어떨까요?
분리하게 되면 어떤 점에서 좋을까요?

2021-09-09 15:53 UTC, BeokBeok commented on data/src/main/java/com/egiwon/data/di/RepositoryModule.kt
> +        ImageRepositoryImpl(imageDataSource)
P1. Binds 어노테이션이 적합해보입니다.

2021-09-09 15:53 UTC, BeokBeok commented on domain/src/main/java/com/egiwon/domain/entity/Image.kt
> +data class Image(
P1. entity 개념은 data 모듈에 있어야합니다.
domain 에서는 entity가 아닌 다른 모델로 정의해주세요

2021-09-09 15:53 UTC, BeokBeok commented on data/src/main/java/com/egiwon/data/ImageDataSource.kt
> +interface ImageDataSource {
P2. internal 키워드를 붙이시고, Module 관련 클래스에도 internal을 붙이시면 빌드가 됩니다. 😄

2021-09-09 15:53 UTC, BeokBeok commented on domain/src/main/java/com/egiwon/domain/usecase/GetRandomImageUseCase.kt
> +class GetRandomImageUseCase @Inject constructor(
P1. UseCase도 DI 관련 클래스를 만들어주세요.

2021-09-09 15:53 UTC, BeokBeok commented on data/src/main/java/com/egiwon/data/response/RandomImageResponse.kt
> +    )
P3. 인터페이스를 활용하면 entity에 mapper 함수를 implementaion 할 수 있어요

```
internal interface DataToDomainMapper<T> {

    fun toDomain(): T
}
```

2021-09-11 13:57 UTC, 2giwon commented on data/src/main/java/com/egiwon/data/di/DataSourceModule.kt
> +        ImageDataSourceImpl(randomImageService)
binds를 사용하니 더 간단하게 구현이 되는데 둘의 차이점이 자동 생성 코드가 발생하는것 말고 다른게 있나요?

좀 찾아보니 binds는 더 복잡하다고는 하던데

2021-09-11 14:04 UTC, BeokBeok commented on data/src/main/java/com/egiwon/data/di/DataSourceModule.kt
> +        ImageDataSourceImpl(randomImageService)
Dagger의 권장사항에 다음과 같이 적혀있습니다.
> Use `@Binds` to tell Dagger which implementation an interface should have.
Use `@Provides` to tell Dagger how to provide classes that your project doesn't own.

ref. https://developer.android.com/training/dependency-injection/dagger-android#best-practices

참고로 자동 코드가 생성되면, 빌드 시간이 더 늘어나게 됩니다.

2021-09-11 14:25 UTC, 2giwon commented on data/src/main/java/com/egiwon/data/di/DataSourceModule.kt
> +        ImageDataSourceImpl(randomImageService)
Binds 는 명시적으로 어떤 구현이 있는 지 파악이 될때 사용하면 되고
Provides는 프로젝트에서 소유하지 않은(명시적으로 선언하지 않으면 알 수 없는) 않았을때 선언하면 된다로 이해하면 될까요?

2021-09-11 14:28 UTC, BeokBeok commented on data/src/main/java/com/egiwon/data/di/DataSourceModule.kt
> +        ImageDataSourceImpl(randomImageService)
레트로핏은 인터페이스를 선언해주면 리플렉션을 통해 내부에서 클래스가 생성되기 때문에, binds를 쓸 수 없습니다 😅

2021-09-11 14:44 UTC, 2giwon commented on data/src/main/java/com/egiwon/data/di/DataSourceModule.kt
> +        ImageDataSourceImpl(randomImageService)
95a3e4861a47a9b69b28a4f972959d927178e79a 수정했습니다

2021-09-11 14:45 UTC, 2giwon commented on data/src/main/java/com/egiwon/data/di/NetworkModule.kt
> +        retrofit.create(RandomImageService::class.java)
서비스를 분리하면 한곳에서 관리할 수 있어서 용이합니다. 유지보수가 편해집니다.

2021-09-11 14:45 UTC, 2giwon commented on data/src/main/java/com/egiwon/data/di/NetworkModule.kt
> +        retrofit.create(RandomImageService::class.java)
83d0e0375580154fc70aa61848e4af9ab2f7386e 수정했습니다.

2021-09-11 14:45 UTC, 2giwon commented on data/src/main/java/com/egiwon/data/di/RepositoryModule.kt
> +        ImageRepositoryImpl(imageDataSource)
a83f43c4af3de43be7aeddb46d1a56eb99990517 수정했습니다.

2021-09-11 14:46 UTC, 2giwon commented on domain/src/main/java/com/egiwon/domain/entity/Image.kt
> +data class Image(
몇일전에 저에게 entity는 domain에 있어야 한다고 하셔서..

2021-09-11 14:46 UTC, 2giwon commented on domain/src/main/java/com/egiwon/domain/entity/Image.kt
> +data class Image(
6922c395dff68b314767f0679d6ce7abe3156191 수정했습니다.

2021-09-11 14:46 UTC, 2giwon commented on data/src/main/java/com/egiwon/data/ImageDataSource.kt
> +interface ImageDataSource {
92096988f59fa1c67dee8e06443c499aae5ab3b8 수정했습니다.

2021-09-11 14:46 UTC, 2giwon commented on domain/src/main/java/com/egiwon/domain/usecase/GetRandomImageUseCase.kt
> +class GetRandomImageUseCase @Inject constructor(
bf2d100fdece480bcdaf43192e88568d15eeec70 수정했습니다.

2021-09-11 14:47 UTC, 2giwon commented on data/src/main/java/com/egiwon/data/response/RandomImageResponse.kt
> +    )
2841eb9d8e90091bdf42141b85f69afc00a8ee00 수정했습니다.

2021-09-11 14:47 UTC, 2giwon reviewed
훌륭한 리뷰입니다.

2021-09-11 14:51 UTC, BeokBeok commented on domain/src/main/java/com/egiwon/domain/entity/Image.kt
> +data class Image(
> 몇일전에 저에게 entity는 domain에 있어야 한다고 하셔서..

이렇게 말씀드리게 된 배경이 있습니다 🙏 
처음에 app 모듈이 domain 모듈에 의존하고, domain 모듈은 data 모듈에 의존하는 구조로 여태까지 알고 있었는데, 스터디를 통해서 data 모듈이 domain 모듈에 의존하는 구조로 변경하게 됨에 따라서 entity가 domain에 있어야하는걸로 이해를 했었습니다 😅 
하지만 의존성만 반대가 됐을 뿐, data 모듈에서 domain 모듈에서 사용하는 모델로 변환해서 전달해주면 된다는 것을 최근에 알게 되었습니다 🙏

2021-09-11 15:00 UTC, BeokBeok requested changes

2021-09-11 15:00 UTC, BeokBeok commented on data/src/main/java/com/egiwon/data/response/RandomImageResponse.kt
> +
```suggestion
```
P3. 한 줄 이상의 빈 라인은 제거하면 어떨까요?

2021-09-11 15:00 UTC, BeokBeok commented on data/src/main/java/com/egiwon/data/di/InterceptorModule.kt
> +class InterceptorModule {
P1. 모듈 관련 클래스에 internal 접근자를 추가해주세요.

2021-09-11 15:00 UTC, BeokBeok commented on data/src/main/java/com/egiwon/data/di/NetworkModule.kt
> +            .build()
```suggestion
    ) = OkHttpClient.Builder()
            .addInterceptor(loggingInterceptor)
            .addInterceptor(interceptor)
            .build()
```
P3. 불필요한 라인은 제거해주면 어떨까요?

2021-09-11 15:00 UTC, BeokBeok commented on data/src/main/java/com/egiwon/data/di/NetworkModule.kt
> +        .baseUrl("https://api.unsplash.com/")
P2. 매직 넘버는 상수로 관리하는 것이 좋습니다.

2021-09-11 15:00 UTC, BeokBeok commented on data/src/main/java/com/egiwon/data/response/RandomImageResponse.kt
> +data class RandomImageResponse (
P1. entity 관련 클래스에 internal 접근자를 추가해주세요.

2021-09-11 15:00 UTC, BeokBeok commented on domain/src/main/java/com/egiwon/domain/usecase/GetRandomImageUseCase.kt
> +class GetRandomImageUseCase @Inject constructor(
P3. CoroutineUseCase를 활용해보는 것도 좋을 것 같아요.

ref. https://github.com/google/iosched/blob/main/shared/src/main/java/com/google/samples/apps/iosched/shared/domain/CoroutineUseCase.kt

2021-09-11 15:27 UTC, 2giwon commented on data/src/main/java/com/egiwon/data/di/InterceptorModule.kt
> +class InterceptorModule {
수정했습니다. 38041a67d41b9c78c2383bbd63653548ad67171c

2021-09-11 15:29 UTC, 2giwon commented on data/src/main/java/com/egiwon/data/di/NetworkModule.kt
> +        .baseUrl("https://api.unsplash.com/")
수정했습니다. 087c5fc0c4332ec94685894d166afc63d9810391

2021-09-11 15:30 UTC, 2giwon commented on data/src/main/java/com/egiwon/data/response/RandomImageResponse.kt
> +data class RandomImageResponse (
수정했습니다. 84d4f3fc024ca44d6a434e54c01b0fb0e8d8c796

2021-09-11 15:32 UTC, 2giwon commented on domain/src/main/java/com/egiwon/domain/usecase/GetRandomImageUseCase.kt
> +class GetRandomImageUseCase @Inject constructor(
이건 좀 더 공부해봐야 알겠습니다.

2021-09-11 15:35 UTC, BeokBeok requested changes

2021-09-11 15:35 UTC, BeokBeok commented on domain/src/main/java/com/egiwon/domain/usecase/GetRandomImageUseCase.kt
> +internal class GetRandomImageUseCase @Inject constructor(
P1. UseCase는 app모듈에서 사용해야하기 때문에 internal 접근자를 제거해주세요.

2021-09-13 13:05 UTC, 2giwon commented on domain/src/main/java/com/egiwon/domain/usecase/GetRandomImageUseCase.kt
> +internal class GetRandomImageUseCase @Inject constructor(
daa2dfaeb7212b36ea54a92f91e4d3b297c12a9a 수정했어요

2021-09-13 13:15 UTC, BeokBeok approved these changes
<img src="https://user-images.githubusercontent.com/48344355/108810482-8fca5400-75ee-11eb-9a24-9931a3877f9d.png" width="30%">

2021-09-13 13:25 UTC, merged